(() => {
'use strict';
const $ = (s) => document.querySelector(s); const $$ = (s) => [...document.querySelectorAll(s)];
const state = { role:null, peer:null, hostConn:null, conns:new Map(), room:null, code:null, bank:[], words:[], idx:-1, phase:'idle', timer:null, deadline:0, answers:new Map(), players:new Map(), history:[], settings:null, me:null };
const screens=['home','hostSetup','lobby','hostGame','joinSetup','studentLobby','studentGame','results'];
let lastRepeatTime = 0;
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('on',x===id)); window.scrollTo(0,0)}
function clean(s){return String(s||'').trim().replace(/\s+/g,' ').slice(0,40)}
function normalize(s){return clean(s).toLowerCase().replace(/[^a-z'-]/g,'')}
function six(){return String(Math.floor(100000+Math.random()*900000))}
function hostPeerId(code){return `talktoday-spelling-${code}`}
function joinLink(code){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('join',code);return u.toString()}
async function loadBank(){if(state.bank.length)return;try{const r=await fetch('bank.json');if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();state.bank=Array.isArray(j)?j:(j.words||j.bank||[])}catch(e){console.error('Failed to load word bank:',e);alert('Could not load word bank (bank.json). Check network connection.');throw e}}
function levelOf(w){return String(w.level||w.cefr||w.CEFR||'').toUpperCase()}
function wordOf(w){return String(w.word||w.spelling||w.term||'').trim()}
function defOf(w){return String(w.definition||w.def||w.meaning||'').trim()}
function sentenceOf(w){return String(w.sentence||w.example||'').trim()}
function pickWords(n,level){let pool=state.bank.filter(x=>wordOf(x).length>1);if(level!=='ALL'){const exact=pool.filter(x=>levelOf(x)===level);if(exact.length>=n)pool=exact} pool=[...pool].sort(()=>Math.random()-.5);const seen=new Set();const out=[];for(const x of pool){const w=wordOf(x).toLowerCase();if(!seen.has(w)){seen.add(w);out.push({word:w,definition:defOf(x),sentence:sentenceOf(x),level:levelOf(x)});if(out.length>=n)break}}return out}
function speak(word){if(!word)return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.72;u.pitch=1;speechSynthesis.speak(u)}
function send(conn,msg){try{if(conn&&conn.open)conn.send(msg)}catch(e){}}
function broadcast(msg){state.conns.forEach(c=>send(c,msg))}
function playerArray(){return [...state.players.values()]}
function sortedPlayers(){return playerArray().sort((a,b)=>b.score-a.score||b.correct-a.correct||a.name.localeCompare(b.name))}
function scoreFor(ms,first){if(!state.settings.speedBonus)return 700+(first?100:0);const s=state.settings.seconds*1000;const frac=Math.max(0,Math.min(1,1-ms/s));return Math.round(500+500*frac)+(first?100:0)}
function renderLobby(){const ps=playerArray();$('#playerCount').textContent=ps.length;$('#startGameBtn').disabled=!ps.length;$('#lobbyPlayers').innerHTML=ps.map(p=>`<div class="player-chip"><b>${esc(p.name)}</b><span>${p.studentId?`ID ${esc(p.studentId)}`:(p.connected?'connected':'reconnecting…')}</span></div>`).join('')||'<div class="hint">Waiting for phones…</div>'}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function createRoom(){await loadBank();state.role='host';state.settings={level:$('#level').value,rounds:+$('#rounds').value,seconds:+$('#seconds').value,mode:$('#mode').value,showDefinition:$('#showDefinition').checked,speedBonus:$('#speedBonus').checked};state.words=pickWords(state.settings.rounds,state.settings.level);if(!state.words.length){alert('No words available.');return} state.code=six();$('#roomCodeBig').textContent=state.code;const url=joinLink(state.code);$('#joinUrl').textContent=url;$('#qr').innerHTML='';new QRCode($('#qr'),{text:url,width:220,height:220,correctLevel:QRCode.CorrectLevel.M});show('lobby');openHostPeer()}
function openHostPeer(){if(state.peer)try{state.peer.destroy()}catch(e){};const p=new Peer(hostPeerId(state.code),{debug:1});state.peer=p;p.on('open',()=>{console.log('Host Peer open:',p.id);$('#roomCodeBig').textContent=state.code});p.on('connection',conn=>{conn.on('data',m=>onHostMessage(conn,m));conn.on('close',()=>removeConn(conn));conn.on('error',()=>removeConn(conn))});p.on('error',e=>{if(e.type==='unavailable-id'){state.code=six();$('#roomCodeBig').textContent=state.code;openHostPeer()}else console.error('Host Peer error:',e)})}
function removeConn(conn){for(const [id,c] of state.conns.entries())if(c===conn){state.conns.delete(id);const p=state.players.get(id);if(p){p.connected=false;if(state.phase==='lobby')state.players.delete(id)}renderLobby();renderHostRanks()}}
function onHostMessage(conn,m){if(!m||typeof m!=='object')return;if(m.type==='join'){const existingId = m.clientId && state.players.has(m.clientId) ? m.clientId : [...state.players.keys()].find(k => {const p = state.players.get(k); return p.name === clean(m.name) && (p.studentId === clean(m.studentId) || (!p.studentId && !m.studentId));});const id = existingId || m.clientId || crypto.randomUUID();state.conns.set(id,conn);if(existingId){const p=state.players.get(id);p.connected=true;p.id=id}else if(state.phase!=='playing'){state.players.set(id,{id,name:clean(m.name)||'Student',studentId:clean(m.studentId),score:0,correct:0,attempts:0,connected:true,eliminated:false})}else{send(conn,{type:'error',message:'Game in progress'});return}send(conn,{type:'joined',clientId:id,code:state.code,settings:state.settings});renderLobby();renderHostRanks();if(state.phase==='playing'||state.phase==='question'){send(conn,{type:'gameStart',total:state.words.length,settings:state.settings});if(state.idx>=0&&state.phase==='question'){const w=state.words[state.idx];send(conn,{type:'question',round:state.idx+1,total:state.words.length,seconds:state.settings.seconds,definition:state.settings.showDefinition?w.definition:'',sentence:w.sentence});const ans=state.answers.get(id);if(ans){send(conn,{type:'answerResult',correct:ans.correct,points:ans.points,score:state.players.get(id).score,rank:0,word:w.word})}}}else if(state.phase==='reveal'){send(conn,{type:'gameStart',total:state.words.length,settings:state.settings});const w=state.words[state.idx];const r=rankRound().findIndex(x=>x.playerId===id);send(conn,{type:'roundReveal',word:w.word,roundRank:r>=0?r+1:null,score:state.players.get(id).score})}return}
 if(m.type==='repeatRequest'&&state.phase==='question'){const now=performance.now();if(now-lastRepeatTime<1000)return;lastRepeatTime=now;const w=state.words[state.idx];if(w)speak(w.word);return}
 if(m.type==='answer'&&state.phase==='question'){const p=state.players.get(m.clientId);if(!p||p.eliminated||state.answers.has(p.id))return;const now=performance.now(),ms=Math.max(0,Math.round(now-state.deadline+state.settings.seconds*1000));const target=state.words[state.idx].word;const ans=normalize(m.answer);const correct=ans===normalize(target);const firstCorrect=correct&&![...state.answers.values()].some(a=>a.correct);const pts=correct?scoreFor(ms,firstCorrect):0;p.attempts++;if(correct){p.correct++;p.score+=pts}else if(state.settings.mode==='elimination')p.eliminated=true;const rec={playerId:p.id,name:p.name,studentId:p.studentId,round:state.idx+1,word:target,answer:ans,correct,ms,points:pts,receivedAt:new Date().toISOString()};state.answers.set(p.id,rec);state.history.push(rec);send(conn,{type:'answerResult',correct,points:pts,score:p.score,rank:0,word:target});renderHostRanks();$('#answeredCount').textContent=`${state.answers.size} answered`;if(activePlayers().every(x=>state.answers.has(x.id)))closeQuestion()}}
function activePlayers(){return playerArray().filter(p=>p.connected&&!p.eliminated)}
function startGame(){state.phase='playing';state.idx=-1;state.history=[];playerArray().forEach(p=>Object.assign(p,{score:0,correct:0,attempts:0,eliminated:false}));broadcast({type:'gameStart',total:state.words.length,settings:state.settings});show('hostGame');nextQuestion()}
function nextQuestion(){clearInterval(state.timer);state.idx++;if(state.idx>=state.words.length||!activePlayers().length){finishGame();return}state.phase='question';state.answers.clear();const w=state.words[state.idx];$('#hostRound').textContent=`${state.idx+1}/${state.words.length}`;$('#statusLine').textContent='SPELL THE WORD';$('#definition').textContent=state.settings.showDefinition?(w.definition||'Listen carefully.'):'Listen carefully.';$('#revealWord').textContent='';$('#answeredCount').textContent='0 answered';$('#nextWordBtn').disabled=true;state.deadline=performance.now()+state.settings.seconds*1000;broadcast({type:'question',round:state.idx+1,total:state.words.length,seconds:state.settings.seconds,definition:state.settings.showDefinition?w.definition:'',sentence:w.sentence});speak(w.word);tickHost();state.timer=setInterval(tickHost,100);renderHostRanks()}
function tickHost(){const left=Math.max(0,state.deadline-performance.now()),n=Math.ceil(left/1000);$('#hostTimer').textContent=n;if(left<=0)closeQuestion()}
function closeQuestion(){if(state.phase!=='question')return;state.phase='reveal';clearInterval(state.timer);const w=state.words[state.idx];$('#statusLine').textContent='ANSWER';$('#revealWord').textContent=w.word.toUpperCase();$('#nextWordBtn').disabled=false;const ranking=rankRound();ranking.forEach((r,i)=>{const c=state.conns.get(r.playerId);send(c,{type:'roundReveal',word:w.word,roundRank:i+1,score:state.players.get(r.playerId)?.score||0})});playerArray().filter(p=>!state.answers.has(p.id)&&p.connected).forEach(p=>send(state.conns.get(p.id),{type:'roundReveal',word:w.word,roundRank:null,score:p.score}));broadcast({type:'scoreboard',players:sortedPlayers().map(publicPlayer)});renderHostRanks()}
function rankRound(){return [...state.answers.values()].sort((a,b)=>(b.correct-a.correct)||(a.ms-b.ms))}
function publicPlayer(p){return {id:p.id,name:p.name,score:p.score,correct:p.correct,attempts:p.attempts,eliminated:p.eliminated}}
function renderHostRanks(){const round=rankRound();const byId=new Map(round.map((x,i)=>[x.playerId,{...x,rank:i+1}]));$('#liveRanks').innerHTML=sortedPlayers().map(p=>{const r=byId.get(p.id);return `<div class="rank-card"><b>${p.eliminated?'☠ ':''}${esc(p.name)} — ${p.score}</b><span>${r?(r.correct?`#${r.rank} correct · ${(r.ms/1000).toFixed(2)}s`:`wrong · ${(r.ms/1000).toFixed(2)}s`):(state.phase==='question'?'thinking…':`${p.correct}/${p.attempts} correct`)}</span></div>`}).join('')}
function finishGame(){state.phase='finished';clearInterval(state.timer);const ps=sortedPlayers();broadcast({type:'gameOver',players:ps.map(publicPlayer)});renderFinal(ps);show('results')}
function renderFinal(ps){$('#finalRanks').innerHTML=ps.map((p,i)=>`<div class="final-row"><div class="place">#${i+1}</div><div><b>${esc(p.name)}</b><div class="hint">${esc(p.studentId?`ID ${p.studentId}`:'')}</div></div><b>${p.score} pts</b><div class="accuracy">${p.correct}/${p.attempts}</div></div>`).join('')}
function downloadCsv(){const rows=[['timestamp','student_id','name','round','word','answer','correct','response_ms','points'],...state.history.map(x=>[x.receivedAt,x.studentId,x.name,x.round,x.word,x.answer,x.correct,x.ms,x.points])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`talk-today-spelling-${state.code}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
function connectStudent(){const code=$('#joinCode').value.replace(/\D/g,'').slice(0,6),name=clean($('#studentName').value),studentId=clean($('#studentId').value);$('#joinError').textContent='';if(code.length!==6||!name){$('#joinError').textContent='Enter the 6-digit room code and your name.';return}state.role='student';state.code=code;state.me={clientId:localStorage.getItem('tt-spell-client')||crypto.randomUUID(),name,studentId,score:0};localStorage.setItem('tt-spell-client',state.me.clientId);localStorage.setItem('tt-spell-name',name);localStorage.setItem('tt-spell-id',studentId);if(state.peer)try{state.peer.destroy()}catch(e){};const p=new Peer(undefined,{debug:1});state.peer=p;$('#connectBtn').disabled=true;$('#connectBtn').textContent='CONNECTING…';p.on('open',()=>{const conn=p.connect(hostPeerId(code),{reliable:true});state.hostConn=conn;conn.on('open',()=>send(conn,{type:'join',clientId:state.me.clientId,name,studentId}));conn.on('data',onStudentMessage);conn.on('error',()=>studentError('Could not connect to that room.'));setTimeout(()=>{if(!conn.open)studentError('Room not found or teacher connection blocked.')},8000)});p.on('error',()=>studentError('Connection error. Try again.'))}
function studentError(msg){$('#joinError').textContent=msg;$('#connectBtn').disabled=false;$('#connectBtn').textContent='JOIN'}
function onStudentMessage(m){if(!m||typeof m!=='object')return;if(m.type==='joined'){state.me.clientId=m.clientId;localStorage.setItem('tt-spell-client',m.clientId);$('#studentLobbyName').textContent=state.me.name;$('#studentLobbyCode').textContent=state.code;show('studentLobby')}
 if(m.type==='gameStart'){state.settings=m.settings;show('studentGame');$('#studentScore').textContent='0 pts'}
 if(m.type==='question'){state.phase='question';state.currentStudentQuestion=m;$('#studentRound').textContent=`${m.round}/${m.total}`;$('#studentState').textContent='LISTEN — THEN TYPE';$('#studentFeedback').textContent='';$('#studentFeedback').className='student-feedback';$('#studentRank').textContent='';$('#answerInput').value='';$('#answerInput').disabled=false;$('#submitAnswerBtn').disabled=false;setTimeout(()=>$('#answerInput').focus(),120);speak('')}
 if(m.type==='answerResult'){state.me.score=m.score;$('#studentScore').textContent=`${m.score} pts`;$('#answerInput').disabled=true;$('#submitAnswerBtn').disabled=true;$('#studentFeedback').textContent=m.correct?`CORRECT +${m.points}`:'LOCKED IN';$('#studentFeedback').className=`student-feedback ${m.correct?'correct':''}`}
 if(m.type==='roundReveal'){state.phase='reveal';$('#answerInput').disabled=true;$('#submitAnswerBtn').disabled=true;$('#studentState').textContent=`ANSWER: ${String(m.word).toUpperCase()}`;$('#studentRank').textContent=m.roundRank?`Round rank #${m.roundRank}`:'No correct answer this round';$('#studentScore').textContent=`${m.score} pts`}
 if(m.type==='gameOver'){const me=m.players.find(x=>x.id===state.me.clientId);const rank=m.players.findIndex(x=>x.id===state.me.clientId)+1;$('#studentState').textContent='GAME OVER';$('#studentFeedback').textContent=rank?`#${rank} — ${me.score} POINTS`:'Finished';$('#studentFeedback').className='student-feedback correct';$('#studentRank').textContent=me?`${me.correct}/${me.attempts} correct`:'';$('#answerInput').disabled=true;$('#submitAnswerBtn').disabled=true}}
function submitStudentAnswer(e){e.preventDefault();if(state.phase!=='question')return;const answer=$('#answerInput').value;if(!normalize(answer))return;send(state.hostConn,{type:'answer',clientId:state.me.clientId,answer});$('#answerInput').disabled=true;$('#submitAnswerBtn').disabled=true;$('#studentFeedback').textContent='ANSWER SENT';$('#studentFeedback').className='student-feedback'}
function closeRoom(){try{state.peer?.destroy()}catch(e){} location.href=location.pathname}
function playAgain(){state.idx=-1;state.phase='lobby';state.words=pickWords(state.settings.rounds,state.settings.level);state.history=[];playerArray().forEach(p=>Object.assign(p,{score:0,correct:0,attempts:0,eliminated:false}));broadcast({type:'joined',code:state.code,settings:state.settings});renderLobby();show('lobby')}
$('#hostBtn').onclick=()=>show('hostSetup');$('#joinBtn').onclick=()=>show('joinSetup');$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#createRoomBtn').onclick=createRoom;$('#startGameBtn').onclick=startGame;$('#nextWordBtn').onclick=nextQuestion;$('#speakBtn').onclick=()=>state.idx>=0&&speak(state.words[state.idx].word);$('#endGameBtn').onclick=finishGame;$('#closeRoomBtn').onclick=closeRoom;$('#connectBtn').onclick=connectStudent;$('#answerForm').onsubmit=submitStudentAnswer;$('#studentSpeak').onclick=()=>send(state.hostConn,{type:'repeatRequest',clientId:state.me?.clientId});$('#downloadCsvBtn').onclick=downloadCsv;$('#playAgainBtn').onclick=playAgain;
const q=new URLSearchParams(location.search);if(q.get('join')){$('#joinCode').value=q.get('join').replace(/\D/g,'').slice(0,6);$('#studentName').value=localStorage.getItem('tt-spell-name')||'';$('#studentId').value=localStorage.getItem('tt-spell-id')||'';show('joinSetup')}
window.addEventListener('beforeunload',()=>{try{state.peer?.destroy()}catch(e){}});
window.__TTLIVE={state,show,normalize,pickWords,scoreFor,rankRound};
})();
